# fly.toml app configuration file generated for reactivities-enjoy on 2023-09-15T14:01:33+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "reactivities-enjoy"
primary_region = "otp"

[build]
  image = "razvanpetruta/reactivities:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  Cloudinary__CloudName="drc9snsil"
  Cloudinary__ApiKey="257136584963489"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
